# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatWindows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from msgList import MsgList


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1009, 503)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 641, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = MsgList(self)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 10, 361, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.__my_device_id_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.__my_device_id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.__my_device_id_label.setObjectName("__my_device_id_label")
        self.horizontalLayout.addWidget(self.__my_device_id_label)
        self.my_device_id = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.my_device_id.setText("")
        self.my_device_id.setAlignment(QtCore.Qt.AlignCenter)
        self.my_device_id.setObjectName("my_device_id")
        self.horizontalLayout.addWidget(self.my_device_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.__my_device_ip_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.__my_device_ip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.__my_device_ip_label.setObjectName("__my_device_ip_label")
        self.horizontalLayout_2.addWidget(self.__my_device_ip_label)
        self.my_device_ip = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.my_device_ip.setText("")
        self.my_device_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.my_device_ip.setObjectName("my_device_ip")
        self.horizontalLayout_2.addWidget(self.my_device_ip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.__other_device_id_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.__other_device_id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.__other_device_id_label.setObjectName("__other_device_id_label")
        self.horizontalLayout_3.addWidget(self.__other_device_id_label)
        self.other_device_id = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.other_device_id.setText("")
        self.other_device_id.setAlignment(QtCore.Qt.AlignCenter)
        self.other_device_id.setObjectName("other_device_id")
        self.horizontalLayout_3.addWidget(self.other_device_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.__other_device_ip_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.__other_device_ip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.__other_device_ip_label.setObjectName("__other_device_ip_label")
        self.horizontalLayout_4.addWidget(self.__other_device_ip_label)
        self.other_device_ip = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.other_device_ip.setText("")
        self.other_device_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.other_device_ip.setObjectName("other_device_ip")
        self.horizontalLayout_4.addWidget(self.other_device_ip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.__if_receive_msg_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.__if_receive_msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.__if_receive_msg_label.setObjectName("__if_receive_msg_label")
        self.horizontalLayout_6.addWidget(self.__if_receive_msg_label)
        self.if_receive_msg = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.if_receive_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.if_receive_msg.setObjectName("if_receive_msg")
        self.horizontalLayout_6.addWidget(self.if_receive_msg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.forward_order_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forward_order_button.sizePolicy().hasHeightForWidth())
        self.forward_order_button.setSizePolicy(sizePolicy)
        self.forward_order_button.setMinimumSize(QtCore.QSize(100, 60))
        self.forward_order_button.setStyleSheet("border-image: url(:/resource/button_hui_qianjin.png);")
        self.forward_order_button.setText("")
        self.forward_order_button.setObjectName("forward_order_button")
        self.horizontalLayout_9.addWidget(self.forward_order_button)
        self.turn_about_order_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turn_about_order_button.sizePolicy().hasHeightForWidth())
        self.turn_about_order_button.setSizePolicy(sizePolicy)
        self.turn_about_order_button.setMinimumSize(QtCore.QSize(100, 60))
        self.turn_about_order_button.setStyleSheet("border-image: url(:/resource/button_hui_xianghouzhuan.png);")
        self.turn_about_order_button.setText("")
        self.turn_about_order_button.setObjectName("turn_about_order_button")
        self.horizontalLayout_9.addWidget(self.turn_about_order_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.turn_left_order_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turn_left_order_button.sizePolicy().hasHeightForWidth())
        self.turn_left_order_button.setSizePolicy(sizePolicy)
        self.turn_left_order_button.setMinimumSize(QtCore.QSize(100, 60))
        self.turn_left_order_button.setStyleSheet("border-image: url(:/resource/button_hui_zuozhuan.png);")
        self.turn_left_order_button.setText("")
        self.turn_left_order_button.setObjectName("turn_left_order_button")
        self.horizontalLayout_8.addWidget(self.turn_left_order_button)
        self.turn_right_order_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turn_right_order_button.sizePolicy().hasHeightForWidth())
        self.turn_right_order_button.setSizePolicy(sizePolicy)
        self.turn_right_order_button.setMinimumSize(QtCore.QSize(100, 60))
        self.turn_right_order_button.setStyleSheet("border-image: url(:/resource/button_hui_xiangyouzhuan.png);")
        self.turn_right_order_button.setText("")
        self.turn_right_order_button.setObjectName("turn_right_order_button")
        self.horizontalLayout_8.addWidget(self.turn_right_order_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.send_msg_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_msg_button.sizePolicy().hasHeightForWidth())
        self.send_msg_button.setSizePolicy(sizePolicy)
        self.send_msg_button.setMinimumSize(QtCore.QSize(100, 60))
        self.send_msg_button.setStyleSheet("border-image: url(:/resource/button_hui_fasongwenben.png);")
        self.send_msg_button.setText("")
        self.send_msg_button.setObjectName("send_msg_button")
        self.horizontalLayout_7.addWidget(self.send_msg_button)
        self.close_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMinimumSize(QtCore.QSize(100, 60))
        self.close_button.setStyleSheet("border-image: url(:/resource/button_guanbi.png);")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_7.addWidget(self.close_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.__my_device_id_label.setText(_translate("Dialog", "本设备ID"))
        self.__my_device_ip_label.setText(_translate("Dialog", "本机IP"))
        self.__other_device_id_label.setText(_translate("Dialog", "对方设备ID"))
        self.__other_device_ip_label.setText(_translate("Dialog", "对方设备IP"))
        self.__if_receive_msg_label.setText(_translate("Dialog", "接收状态"))
        self.if_receive_msg.setText(_translate("Dialog", "未接收"))

import chatSource_rc
